// <auto-generated />
using System;
using DeskFlow;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeskFlow.Migrations
{
    [DbContext(typeof(DeskFlowDbContext))]
    [Migration("20260923140754_ajusteChamado")]
    partial class ajusteChamado
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DeskFlow.Models.Categoria", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(50)")
                        .HasColumnName("IdCategoria");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)")
                        .HasColumnName("NomeCategoria");

                    b.HasKey("Id");

                    b.ToTable("Tb_Categoria", (string)null);
                });

            modelBuilder.Entity("DeskFlow.Models.Chamado", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataAbertura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataFechamento")
                        .HasColumnType("datetime2");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("varchar(500)")
                        .HasColumnName("DescricaoChamado");

                    b.Property<string>("Prioridade")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("PrioridadeChamado");

                    b.Property<string>("SolicitanteNome")
                        .IsRequired()
                        .HasColumnType("varchar(150)")
                        .HasColumnName("SolicitanteChamado");

                    b.Property<string>("Solucao")
                        .HasColumnType("varchar(500)")
                        .HasColumnName("SolucaoChamado");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("varchar(50)")
                        .HasColumnName("StatusChamado");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("varchar(250)")
                        .HasColumnName("TituloChamado");

                    b.HasKey("Id");

                    b.ToTable("Chamado");
                });

            modelBuilder.Entity("DeskFlow.Models.Interacao", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ChamadoId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DataRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Mensagem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ChamadoId");

                    b.ToTable("Interacao");
                });

            modelBuilder.Entity("DeskFlow.Models.Interacao", b =>
                {
                    b.HasOne("DeskFlow.Models.Chamado", null)
                        .WithMany("Comentarios")
                        .HasForeignKey("ChamadoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DeskFlow.Models.Chamado", b =>
                {
                    b.Navigation("Comentarios");
                });
#pragma warning restore 612, 618
        }
    }
}
